nelmio_api_doc:
    documentation:
        host: api.appli-v.net
#        host: localhost
        schemes: [https]
#        schemes: [http]
        info:
            title: Appli-V
            description: API used for Energy Academy
            version: '0.14'
        securityDefinitions:
            Bearer:
                type: apiKey
                description: 'Authorization: Bearer {jwt}'
                name: Authorization
                in: header
        security:
            - Bearer: []
    areas:
        path_patterns:
            - ^/((?!api|login|signin|signup|user).*$)
