security:
    encoders:
        App\Entity\User: bcrypt
    role_hierarchy:
        ROLE_MODERATOR: 'ROLE_USER'
        ROLE_ADMIN: [ROLE_MODERATOR, ROLE_USER]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_MODERATOR, ROLE_USER]
    providers:
        c975_l_userbundle:
            entity:
                class: App\Entity\User
    access_decision_manager:
        strategy: unanimous
        allow_if_all_abstain: true
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            pattern: ^/
            provider: c975_l_userbundle
            form_login:
                login_path: user_signin
                check_path: user_signin
                default_target_path: user_dashboard
                csrf_token_generator: security.csrf.token_manager
            json_login:
                check_path: user_api_authenticate
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 31536000
                path: /
                secure: true
            anonymous: true
            logout_on_user_change: true
            logout:
                path: user_signout
                handlers: [c975L\UserBundle\Listener\LogoutListener]
            guard:
                authenticators:
                    - c975L\UserBundle\Security\TokenAuthenticator
    access_control:
