c975LUser:
    roleNeeded: ROLE_ADMIN
    signup: true
    signupForm: null
    profileForm: null
    signinAttempts: 5
    touUrl: 'conditions-utilisation'
    avatar: false
    entity: c975L\UserBundle\Entity\UserLight
    social: false
    address: false
    business: false
    multilingual: false
    hwiOauth: false
    publicProfile: false
    databaseEmail: false
    archiveUser: false
    formLayout: bootstrap_3_layout
    api: true
    apiOnly: true
c975LCommon:
    site: 'EnergyAcademy'
    author: 'EnergyAcademy'
    firstOnlineDate: '2018-10-18'
    logo: null
c975LEmail:
    sentFrom: contact@975l.com
